name: Check Next.js project

on: pull_request

jobs:
  check:
    name: Check project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-next-js-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-next-js-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-next-js-

      - name: Install dependencies
        run: pnpm install

      - name: Check Typescript errors
        run: pnpm run ts:check

      - name: Check ESLint errors
        run: pnpm run lint:check